### ISSUE TITLE
normalize bag

### ISSUE THREAD

**Issue by sfcl** [gmr/email-normalize#2]
Not work 
    
email = 'f.o.o+bar@mail.ru'
normalized = normalize(email)
print(email, normalized)

#return  'f.o.o+bar@mail.ru'

**Comment by gmr** [comment]
So mail.ru follows gmail's conventions for plus and dot addressing?

**Comment by sfcl** [comment]
https://help.mail.ru/mail-help/registration/name

In the name box you can use:
* any Latin characters (a-z, A-Z);
* any digit (0-9);
* special characters: ("-"), ("_") and (".") — these characters can't go to each other and to be the first and last characters in the name of the mailbox.

**Comment by gmr** [comment]
I don't see any documentation for mail.ru that indicates they support transparent aliasing of email addresses. IE that `foo@mail.ru` is the same as `foo+bar@mail.ru` or `foo-bar@mail.ru`.

If you can find documentation to that extent, please provide it and I'll get them added. The documentation you created had to do with account creation, not email aliasing.
